FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5001
EXPOSE 5001

COPY [".", "app/"]
RUN dotnet restore "app/Gadget.Server/Gadget.Server.csproj"
COPY . .
WORKDIR "/app/Gadget.Server"
RUN dotnet build "Gadget.Server.csproj" -c Release -o /app/build


FROM build AS publish
RUN dotnet publish "Gadget.Server.csproj" -c Release -o /app/publish



FROM publish AS final
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gadget.Server.dll"]
