{
 "title": "agents",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ag",
    "query": "SELECT DISTINCT(Agent) FROM BasicMetrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Services running",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Date),\n   ServicesRunning as value,\n  'SVC RUNNING' as metric\nFROM\n  BasicMetrics\nWHERE\n  $__timeFilter(Date) and Agent = $ag\nORDER BY\n  Date ASC"
    }
   ]
  },
  {
   "title": "Services total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Date),\n   ServicesCount as value,\n  'Services total' as metric\nFROM\n  BasicMetrics\nWHERE\n  $__timeFilter(Date) and Agent = $ag\nORDER BY\n  Date ASC"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Date),\n   CpuPercentUsage as value,\n  'CPU' as metric\nFROM\n  BasicMetrics\nWHERE\n  $__timeFilter(Date) and Agent = $ag\nORDER BY\n  Date ASC"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Date),\n   MemoryFree as value,\n  'MEMORY' as metric\nFROM\n  BasicMetrics\nWHERE\n  $__timeFilter(Date) and Agent = $ag\nORDER BY\n  Date ASC"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(Date),\n   DiscOccupied as value,\n  'DISK' as metric\nFROM\n  BasicMetrics\nWHERE\n  $__timeFilter(Date) and Agent = $ag\nORDER BY\n  Date ASC"
    }
   ]
  }
 ]
}